import { defineConfig } from "oxlint"

export const defineReactConfig = (files: Array<string>) =>
  defineConfig({
    overrides: [
      {
        files,
        plugins: ["react", "react-perf", "jsx-a11y"],
        rules: {
          "import/extensions": "deny",
          "jsx-a11y/alt-text": "off",
          "jsx-a11y/anchor-has-content": "error",
          "jsx-a11y/anchor-is-valid": "error",
          "jsx-a11y/aria-activedescendant-has-tabindex": "error",
          "jsx-a11y/aria-props": "error",
          "jsx-a11y/aria-proptypes": "error",
          "jsx-a11y/aria-role": "error",
          "jsx-a11y/aria-unsupported-elements": "error",
          "jsx-a11y/autocomplete-valid": "error",
          "jsx-a11y/click-events-have-key-events": "off",
          "jsx-a11y/heading-has-content": "error",
          "jsx-a11y/html-has-lang": "error",
          "jsx-a11y/iframe-has-title": "error",
          "jsx-a11y/img-redundant-alt": "error",
          "jsx-a11y/label-has-associated-control": "error",
          "jsx-a11y/lang": "error",
          "jsx-a11y/media-has-caption": "error",
          "jsx-a11y/mouse-events-have-key-events": "error",
          "jsx-a11y/no-access-key": "error",
          "jsx-a11y/no-aria-hidden-on-focusable": "error",
          "jsx-a11y/no-autofocus": "off",
          "jsx-a11y/no-distracting-elements": "error",
          "jsx-a11y/no-noninteractive-tabindex": "error",
          "jsx-a11y/no-redundant-roles": "error",
          "jsx-a11y/no-static-element-interactions": "off",
          "jsx-a11y/prefer-tag-over-role": "off",
          "jsx-a11y/role-has-required-aria-props": "off",
          "jsx-a11y/role-supports-aria-props": "error",
          "jsx-a11y/scope": "error",
          "jsx-a11y/tabindex-no-positive": "error",
          "react-perf/jsx-no-jsx-as-prop": "off",
          "react-perf/jsx-no-new-array-as-prop": "error",
          "react-perf/jsx-no-new-function-as-prop": "off",
          "react-perf/jsx-no-new-object-as-prop": "off",
          "react/button-has-type": "off",
          "react/exhaustive-deps": "off",
          "react/forbid-component-props": "off",
          "react/function-component-definition": "off",
          "react/iframe-missing-sandbox": "error",
          "react/jsx-boolean-value": "error",
          "react/jsx-curly-brace-presence": "error",
          "react/jsx-filename-extension": "off",
          "react/jsx-fragments": "error",
          "react/jsx-handler-names": "off",
          "react/jsx-key": "error",
          "react/jsx-max-depth": "off",
          "react/jsx-no-comment-textnodes": "error",
          "react/jsx-no-constructed-context-values": "error",
          "react/jsx-no-duplicate-props": "error",
          "react/jsx-no-literals": "off",
          "react/jsx-no-script-url": "error",
          "react/jsx-no-target-blank": "error",
          "react/jsx-no-useless-fragment": "off",
          "react/jsx-props-no-spread-multi": "error",
          "react/jsx-props-no-spreading": "off",
          "react/no-array-index-key": "off",
          "react/no-children-prop": "off",
          "react/no-danger": "off",
          "react/no-danger-with-children": "error",
          "react/no-direct-mutation-state": "error",
          "react/no-multi-comp": "off",
          "react/no-unescaped-entities": "off",
          "react/no-unstable-nested-components": "off",
          "react/only-export-components": "off",
          "react/react-in-jsx-scope": "off",
          "react/rules-of-hooks": "error",
          "react/self-closing-comp": "error",
          "react/void-dom-elements-no-children": "error",
        },
      },
    ],
  })
