allowBuilds:
  msgpackr-extract: true
catalog:
  "@effect/tsgo": 0.45.0
  "@effect/language-service": ^0.87.2
  "@effect/platform-node": ^4.0.0-rc.115
  "@oxlint/plugins": 1.82.0
  "@types/node": ^26.6.1
  diff: ^8.0.3
  effect: ^4.0.0-rc.115
  oxfmt: ^0.68.0
  oxlint: 1.82.0
  typescript: ^7.0.2
  yaml: ^2.9.1
