packages:
  - repo-util

catalog:
  "@changesets/cli": ^2.30.0
  "@effect/language-service": 0.85.1
  "@effect/platform-node": ^4.0.0-beta.50
  "@types/node": ^25.6.0
  dedent: ^1.7.1
  diff: ^8.0.3
  dprint: ^0.54.0
  effect: ^4.0.0-beta.50
  oxlint: ^1.60.0
  oxfmt: ^0.42.0
  ts-patch: ^3.3.0
  typescript: ^6.0.2
  yaml: ^2.8.3
